import { Shipment, Alert, DashboardStats, AnalyticsData, User } from './types'

export const mockUser: User = {
  id: '1',
  name: 'Alex Morgan',
  email: 'alex@smartlogistics.com',
  role: 'admin',
}

export const mockShipments: Shipment[] = [
  {
    id: 'SHP-001',
    origin: 'New York',
    destination: 'Los Angeles',
    status: 'in-transit',
    progress: 65,
    eta: '2 days',
    weight: '450 kg',
    createdAt: '2024-01-15',
    riskScore: 34,
    lastUpdate: '2024-01-18 14:32',
    route: [
      { city: 'New York', status: 'completed', timestamp: '2024-01-15 08:30' },
      { city: 'Chicago', status: 'completed', timestamp: '2024-01-16 14:20' },
      { city: 'Denver', status: 'current', timestamp: '2024-01-17 11:45' },
      { city: 'Las Vegas', status: 'upcoming' },
      { city: 'Los Angeles', status: 'upcoming' },
    ],
  },
  {
    id: 'SHP-002',
    origin: 'Miami',
    destination: 'Seattle',
    status: 'in-transit',
    progress: 42,
    eta: '3 days',
    weight: '320 kg',
    createdAt: '2024-01-16',
    riskScore: 56,
    lastUpdate: '2024-01-18 13:15',
    route: [
      { city: 'Miami', status: 'completed', timestamp: '2024-01-16 09:15' },
      { city: 'Atlanta', status: 'completed', timestamp: '2024-01-17 16:30' },
      { city: 'St. Louis', status: 'current', timestamp: '2024-01-18 10:20' },
      { city: 'Denver', status: 'upcoming' },
      { city: 'Seattle', status: 'upcoming' },
    ],
  },
  {
    id: 'SHP-003',
    origin: 'Boston',
    destination: 'San Francisco',
    status: 'delivered',
    progress: 100,
    eta: 'Delivered',
    weight: '280 kg',
    createdAt: '2024-01-10',
    riskScore: 8,
    lastUpdate: '2024-01-17 11:20',
    route: [
      { city: 'Boston', status: 'completed', timestamp: '2024-01-10 07:00' },
      { city: 'Philadelphia', status: 'completed', timestamp: '2024-01-11 13:30' },
      { city: 'Pittsburgh', status: 'completed', timestamp: '2024-01-12 15:45' },
      { city: 'Chicago', status: 'completed', timestamp: '2024-01-13 18:00' },
      { city: 'Denver', status: 'completed', timestamp: '2024-01-15 10:30' },
      { city: 'San Francisco', status: 'completed', timestamp: '2024-01-17 11:20' },
    ],
  },
  {
    id: 'SHP-004',
    origin: 'Dallas',
    destination: 'Portland',
    status: 'delayed',
    progress: 38,
    eta: '4 days',
    weight: '390 kg',
    createdAt: '2024-01-14',
    riskScore: 78,
    lastUpdate: '2024-01-18 12:45',
    route: [
      { city: 'Dallas', status: 'completed', timestamp: '2024-01-14 06:00' },
      { city: 'Oklahoma City', status: 'completed', timestamp: '2024-01-15 14:15' },
      { city: 'Kansas City', status: 'current', timestamp: '2024-01-18 09:30' },
      { city: 'Denver', status: 'upcoming' },
      { city: 'Portland', status: 'upcoming' },
    ],
  },
  {
    id: 'SHP-005',
    origin: 'Phoenix',
    destination: 'New York',
    status: 'pending',
    progress: 0,
    eta: '5 days',
    weight: '520 kg',
    createdAt: '2024-01-18',
    riskScore: 22,
    lastUpdate: '2024-01-18 10:00',
    route: [
      { city: 'Phoenix', status: 'upcoming' },
      { city: 'Albuquerque', status: 'upcoming' },
      { city: 'Dallas', status: 'upcoming' },
      { city: 'Memphis', status: 'upcoming' },
      { city: 'New York', status: 'upcoming' },
    ],
  },
]

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    message: 'Shipment SHP-004 delayed due to weather conditions',
    type: 'warning',
    timestamp: '2024-01-18 16:32',
    shipmentId: 'SHP-004',
    severity: 'high',
    alertType: 'weather',
    status: 'active',
  },
  {
    id: 'ALT-002',
    message: 'SHP-003 delivered successfully to San Francisco',
    type: 'success',
    timestamp: '2024-01-17 11:20',
    shipmentId: 'SHP-003',
    severity: 'low',
    alertType: 'optimization',
    status: 'resolved',
  },
  {
    id: 'ALT-003',
    message: 'High traffic detected on Route 70, ETA adjusted',
    type: 'warning',
    timestamp: '2024-01-18 15:45',
    shipmentId: 'SHP-002',
    severity: 'medium',
    alertType: 'traffic',
    status: 'active',
  },
  {
    id: 'ALT-004',
    message: 'System maintenance scheduled for tonight',
    type: 'error',
    timestamp: '2024-01-18 18:15',
    severity: 'medium',
    alertType: 'system',
    status: 'active',
  },
  {
    id: 'ALT-005',
    message: 'SHP-001 route optimized, saving 45 minutes',
    type: 'success',
    timestamp: '2024-01-18 14:30',
    shipmentId: 'SHP-001',
    severity: 'low',
    alertType: 'optimization',
    status: 'resolved',
  },
]

export const mockStats: DashboardStats = {
  totalShipments: 1247,
  activeShipments: 43,
  deliveredToday: 12,
  systemHealth: 98,
  revenue: 145000,
  efficiency: 94,
}

export const mockAnalyticsData: AnalyticsData[] = [
  { date: 'Jan 10', deliveries: 45, revenue: 32000, efficiency: 92 },
  { date: 'Jan 11', deliveries: 52, revenue: 38000, efficiency: 94 },
  { date: 'Jan 12', deliveries: 48, revenue: 35000, efficiency: 93 },
  { date: 'Jan 13', deliveries: 61, revenue: 44000, efficiency: 96 },
  { date: 'Jan 14', deliveries: 55, revenue: 40000, efficiency: 95 },
  { date: 'Jan 15', deliveries: 58, revenue: 42000, efficiency: 94 },
  { date: 'Jan 16', deliveries: 62, revenue: 45000, efficiency: 96 },
  { date: 'Jan 17', deliveries: 58, revenue: 42000, efficiency: 95 },
]

import { AdminStats, UserProfile, UserDashboardStats, TrackingEvent, FlipCardData } from './types'

export const mockAdminStats: AdminStats = {
  totalUsers: 284,
  activeUsers: 47,
  totalRevenue: 1_847_320,
  revenueGrowth: 18.4,
  totalShipments: 12_470,
  shipmentsGrowth: 12.5,
  systemUptime: 99.97,
  pendingApprovals: 7,
  alertsToday: 12,
  resolvedToday: 9,
  avgDeliveryTime: 38.4,
  customerSatisfaction: 4.7,
}

export const mockUserProfiles: UserProfile[] = [
  { id: 'U1', name: 'Alex Morgan', email: 'alex@smartlogistics.com', role: 'admin', department: 'Operations', joinedDate: '2022-03-15', activeShipments: 8, totalShipmentsHandled: 1240, performanceScore: 96, lastLogin: '2024-01-18 09:22' },
  { id: 'U2', name: 'Sam Chen', email: 'sam@smartlogistics.com', role: 'operator', department: 'Logistics', joinedDate: '2023-01-10', activeShipments: 5, totalShipmentsHandled: 432, performanceScore: 88, lastLogin: '2024-01-18 08:45' },
  { id: 'U3', name: 'Maria Garcia', email: 'maria@smartlogistics.com', role: 'manager', department: 'Supply Chain', joinedDate: '2021-07-20', activeShipments: 12, totalShipmentsHandled: 2180, performanceScore: 94, lastLogin: '2024-01-18 10:01' },
]

export const mockUserDashboardStats: UserDashboardStats = {
  myActiveShipments: 5,
  myDeliveredThisMonth: 28,
  myPendingActions: 3,
  myAlerts: 2,
  onTimeDeliveryRate: 91.4,
  avgHandlingTime: 22.6,
}

export const mockTrackingEvents: TrackingEvent[] = [
  { id: 'TE1', shipmentId: 'SHP-001', event: 'Package picked up', location: 'New York Warehouse', timestamp: '2024-01-15 08:30', status: 'completed', icon: 'warehouse' },
  { id: 'TE2', shipmentId: 'SHP-001', event: 'In transit - highway', location: 'I-80, Ohio', timestamp: '2024-01-16 14:20', status: 'completed', icon: 'truck' },
  { id: 'TE3', shipmentId: 'SHP-001', event: 'At distribution hub', location: 'Denver Hub', timestamp: '2024-01-17 11:45', status: 'current', icon: 'warehouse' },
  { id: 'TE4', shipmentId: 'SHP-001', event: 'Out for delivery', location: 'Las Vegas Route', timestamp: '', status: 'upcoming', icon: 'truck' },
  { id: 'TE5', shipmentId: 'SHP-001', event: 'Delivered', location: 'Los Angeles', timestamp: '', status: 'upcoming', icon: 'check' },
]

export const mockAdminFlipCards: FlipCardData[] = [
  {
    id: 'AFC1',
    frontTitle: 'Total Revenue',
    frontValue: '$1.84M',
    frontSubtitle: '+18.4% this month',
    frontIcon: 'DollarSign',
    frontColor: 'emerald',
    backTitle: 'Revenue Breakdown',
    backContent: 'Revenue is up 18.4% driven by new enterprise contracts and increased shipment volume in Q1.',
    backStats: [
      { label: 'Enterprise', value: '$1.2M' },
      { label: 'SMB', value: '$480K' },
      { label: 'Individual', value: '$163K' },
    ],
    backAction: { label: 'View Analytics', href: '/admin/analytics' },
  },
  {
    id: 'AFC2',
    frontTitle: 'Active Users',
    frontValue: '47',
    frontSubtitle: 'of 284 total users',
    frontIcon: 'Users',
    frontColor: 'cyan',
    backTitle: 'User Activity',
    backContent: 'Peak usage at 10AM–2PM. 47 users online now across 3 departments.',
    backStats: [
      { label: 'Operations', value: '18' },
      { label: 'Logistics', value: '21' },
      { label: 'Supply Chain', value: '8' },
    ],
    backAction: { label: 'Manage Users', href: '/admin/users' },
  },
  {
    id: 'AFC3',
    frontTitle: 'System Health',
    frontValue: '99.97%',
    frontSubtitle: 'Uptime last 30 days',
    frontIcon: 'Activity',
    frontColor: 'violet',
    backTitle: 'Infrastructure Status',
    backContent: 'All systems operational. Last incident: 42 days ago (3-minute DB hiccup).',
    backStats: [
      { label: 'API Latency', value: '42ms' },
      { label: 'DB Response', value: '8ms' },
      { label: 'Error Rate', value: '0.003%' },
    ],
    backAction: { label: 'View Logs', href: '/admin/system' },
  },
  {
    id: 'AFC4',
    frontTitle: 'Pending Approvals',
    frontValue: '7',
    frontSubtitle: '2 urgent',
    frontIcon: 'ClipboardCheck',
    frontColor: 'amber',
    backTitle: 'Approval Queue',
    backContent: '2 high-priority shipment overrides, 3 new user registrations, 2 route change requests awaiting review.',
    backStats: [
      { label: 'Shipments', value: '2 urgent' },
      { label: 'Users', value: '3 pending' },
      { label: 'Routes', value: '2 requests' },
    ],
    backAction: { label: 'Review All', href: '/admin/approvals' },
  },
]

export const mockUserFlipCards: FlipCardData[] = [
  {
    id: 'UFC1',
    frontTitle: 'My Active Shipments',
    frontValue: '5',
    frontSubtitle: '2 arriving today',
    frontIcon: 'Package',
    frontColor: 'cyan',
    backTitle: 'Shipment Breakdown',
    backContent: 'You have 5 active shipments: 3 in-transit, 1 at hub, 1 pending pickup.',
    backStats: [
      { label: 'In Transit', value: '3' },
      { label: 'At Hub', value: '1' },
      { label: 'Pending', value: '1' },
    ],
    backAction: { label: 'View Shipments', href: '/user-dashboard/my-shipments' },
  },
  {
    id: 'UFC2',
    frontTitle: 'On-Time Rate',
    frontValue: '91.4%',
    frontSubtitle: 'Last 30 days',
    frontIcon: 'Clock',
    frontColor: 'emerald',
    backTitle: 'Delivery Performance',
    backContent: 'Your on-time delivery rate is above the team average of 87%. Best performance on East Coast routes.',
    backStats: [
      { label: 'On Time', value: '26 / 28' },
      { label: 'Delayed', value: '2' },
      { label: 'Team Avg', value: '87%' },
    ],
    backAction: { label: 'View History', href: '/user-dashboard/history' },
  },
  {
    id: 'UFC3',
    frontTitle: 'Pending Actions',
    frontValue: '3',
    frontSubtitle: '1 needs reply today',
    frontIcon: 'Bell',
    frontColor: 'amber',
    backTitle: 'Action Items',
    backContent: '1 customs form due by 5PM today, 1 weight discrepancy needs review, 1 signature confirmation pending.',
    backStats: [
      { label: 'Customs Form', value: 'Due 5PM' },
      { label: 'Weight Review', value: '1 item' },
      { label: 'Signature', value: 'Pending' },
    ],
    backAction: { label: 'View Actions', href: '/user-dashboard/actions' },
  },
  {
    id: 'UFC4',
    frontTitle: 'Performance Score',
    frontValue: '88 / 100',
    frontSubtitle: '+4 pts this month',
    frontIcon: 'Star',
    frontColor: 'violet',
    backTitle: 'Score Breakdown',
    backContent: 'Your score is based on delivery accuracy, response time, and documentation completeness.',
    backStats: [
      { label: 'Accuracy', value: '94%' },
      { label: 'Response Time', value: '92%' },
      { label: 'Docs', value: '78%' },
    ],
    backAction: { label: 'Improve Score', href: '/user-dashboard/performance' },
  },
]

