export const MOCK_SHIPMENTS = [
  {
    id: 'sc-001',
    origin: 'Mumbai',
    destination: 'Delhi',
    status: 'in-transit',
    current_location: 'Jaipur Transit Hub',
    eta: '2024-12-28',
    route: ['Mumbai', 'Delhi'],
    alternate_route: ['Mumbai', 'Jaipur', 'Delhi'],
    tracking_id: 'IND001',
    weight: 12,
    package_type: 'Electronics',
  },
  {
    id: 'sc-002',
    origin: 'Bangalore',
    destination: 'Chennai',
    status: 'delivered',
    current_location: 'Chennai Delivery Hub',
    eta: '2024-12-26',
    route: ['Bangalore', 'Chennai'],
    alternate_route: ['Bangalore', 'Vellore', 'Chennai'],
    tracking_id: 'IND002',
    weight: 5,
    package_type: 'Clothing',
  },
  {
    id: 'sc-003',
    origin: 'Hyderabad',
    destination: 'Pune',
    status: 'pending',
    current_location: 'Hyderabad Pickup Hub',
    eta: '2024-12-30',
    route: ['Hyderabad', 'Pune'],
    alternate_route: ['Hyderabad', 'Solapur', 'Pune'],
    tracking_id: 'IND003',
    weight: 25,
    package_type: 'Furniture',
  },
  {
    id: 'sc-004',
    origin: 'Kolkata',
    destination: 'Bhubaneswar',
    status: 'delayed',
    current_location: 'Kharagpur Checkpoint',
    eta: '2024-12-29',
    route: ['Kolkata', 'Bhubaneswar'],
    alternate_route: ['Kolkata', 'Balasore', 'Bhubaneswar'],
    tracking_id: 'IND004',
    weight: 8,
    package_type: 'Medical',
  },
  {
    id: 'sc-005',
    origin: 'Delhi',
    destination: 'Amritsar',
    status: 'in-transit',
    current_location: 'Ludhiana Transit',
    eta: '2024-12-27',
    route: ['Delhi', 'Amritsar'],
    alternate_route: ['Delhi', 'Ambala', 'Amritsar'],
    tracking_id: 'IND005',
    weight: 3,
    package_type: 'Documents',
  },
  {
    id: 'sc-006',
    origin: 'Ahmedabad',
    destination: 'Surat',
    status: 'in-transit',
    current_location: 'Anand Transit',
    eta: '2024-12-27',
    route: ['Ahmedabad', 'Surat'],
    alternate_route: ['Ahmedabad', 'Vadodara', 'Surat'],
    tracking_id: 'IND006',
    weight: 18,
    package_type: 'Auto Parts',
  },
]

export const MOCK_RISKS = {
  'sc-001': {
    riskScore: 72,
    riskLevel: 'high',
    weatherImpact: 28,
    trafficImpact: 44,
    weatherCondition: 'Storm',
    trafficType: 'Heavy',
  },
  'sc-002': {
    riskScore: 12,
    riskLevel: 'low',
    weatherImpact: 5,
    trafficImpact: 7,
    weatherCondition: 'Clear',
    trafficType: 'Light',
  },
  'sc-003': {
    riskScore: 45,
    riskLevel: 'medium',
    weatherImpact: 15,
    trafficImpact: 30,
    weatherCondition: 'Cloudy',
    trafficType: 'Moderate',
  },
  'sc-004': {
    riskScore: 85,
    riskLevel: 'high',
    weatherImpact: 40,
    trafficImpact: 45,
    weatherCondition: 'Rain',
    trafficType: 'Congested',
  },
  'sc-005': {
    riskScore: 30,
    riskLevel: 'low',
    weatherImpact: 10,
    trafficImpact: 20,
    weatherCondition: 'Clear',
    trafficType: 'Light',
  },
  'sc-006': {
    riskScore: 55,
    riskLevel: 'medium',
    weatherImpact: 20,
    trafficImpact: 35,
    weatherCondition: 'Fog',
    trafficType: 'Moderate',
  },
}
